# Generated by Django 4.0.2 on 2022-02-23 21:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='a',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 23, 21, 53, 37, 122043)),
        ),
    ]
